#ifndef STRING_H
#define STRING_H
#include <stdint.h>
// <auto-generated:c-header-generator>
#ifdef __cplusplus
extern "C" {
#endif
void *memset(void *s, int c, size_t n);

void *memcpy(void *dest, const void *src, size_t n);

size_t strlen(const char* str);

#endif
// </auto-generated:c-header-generator>
